fix checks

diff --git a/bftools/scripts/dcs b/bftools/scripts/dcs
--- a/bftools/scripts/dcs
+++ b/bftools/scripts/dcs
@@ -12,26 +12,49 @@ if echo "$1" | grep -Eq "[[:space:]]"; then
     exit 2
 fi
 
-if test -d "${HOME}/bfnext/${2}"; then
-    echo "git path ${2} not found, or not a directory"
+if ! test -d "${HOME}/bfnext/${2}"; then
+    echo "git path ${HOME}/bfnext/${2} not found, or not a directory"
+    exit 3
 fi
 
-if test -f "${HOME}/bfnext/${2}/$3"; then
-    echo "mission ${3} not found in ${2}"
+if ! test -f "${HOME}/bfnext/${2}/${3}"; then
+    echo "mission ${HOME}/bfnext/${2}/${3} not found in ${2}"
+    exit 4
 fi
 
 NAME="$1"
 DCS="$HOME/.wine/drive_c/Program Files/Eagle Dynamics/DCS World OpenBeta Server"
 DATA="$HOME/.wine/drive_c/users/dcs/Saved Games/$NAME"
 BFLOG="${DATA}/Logs/bfnext.txt"
-INSTALLED_MIZ="$(ls "${DATA}/Missions")"
-INSTALLED_CFG="$(ls "${DATA}/*_CFG")"
+INSTALLED_MIZ="${DATA}/Missions/$(ls "${DATA}"/Missions)"
+INSTALLED_CFG="$(ls "${DATA}"/*_CFG)"
 GIT_PATH="$2"
 MIZ_NAME="$3"
-GIT_CFG="$(ls "${GIT_PATH}/*_CFG")"
+GIT_CFG="$(ls "${HOME}/bfnext/${GIT_PATH}"/*_CFG)"
+
+if ! test -d "$DCS"; then
+    echo "dcs install directory missing"
+    exit 8
+fi
+
+if ! test -d "$DATA"; then
+    echo "dcs data dir missing, wrong name?"
+    exit 8
+fi
+
+if ! test -f "$INSTALLED_MIZ"; then
+    echo "missing installed miz $INSTALLED_MIZ"
+    exit 9
+fi
+
+if ! test -f "$INSTALLED_CFG"; then
+    echo "missing installed config $INSTALLED_CFG"
+    exit 10
+fi
 
 if test -z "$GIT_CFG" -o ! -f "$GIT_CFG"; then
     echo "$GIT_CFG not found or not a file"
+    exit 5
 fi
 
 function update_from_git {
